state = {
    "campaign_name": "My Epic Campaign",
    "campaign_description": "An epic adventure awaits...",
    "campaign_rank": "15",
    "campaign_icon": "units/elves-wood/lord.png",
    "campaign_image": "campaign_image.png",
    "easy_img": "units/elves-wood/fighter.png",
    "normal_img": "units/elves-wood/lord.png",
    "hard_img": "units/elves-wood/high-lord.png",
    "easy_label": "Beginner",
    "normal_label": "Normal",
    "hard_label": "Challenging",
    "wesnoth_directory": "C:/Program Files/Battle for Wesnoth 1.18.3",
    "imported_campaign_path": "",
    "extra_addon_path": "",
    "discovered_units": [],
    "scenarios": [],           
    "current_index": None,     
    "view_mode": "scenario",   
    "scenario_list_frame": None,
    "center_content_frame": None,
    "scenario_title_input": None,
    "generate_pbl": True,
    "pbl_type": "campaign",
    "pbl_version": "1.0.0",
    "pbl_author": "",
    "pbl_email": "",
    "pbl_passphrase": ""
}
